[nfs]
172.31.33.193 ansible_ssh_user=ec2-user

[webservers]
172.31.33.53 ansible_ssh_user=ec2-user
172.31.42.80 ansible_ssh_user=ec2-user

[db]
172.31.42.47 ansible_ssh_user=ubuntu

[lb]
172.31.44.149 ansible_ssh_user=ubuntu