[tooling]
172.31.26.143 ansible_ssh_user=ec2-user
172.31.18.71 ansible_ssh_user=ec2-user

[todo]
172.31.44.99 ansible_ssh_user=ec2-user

[lb]
172.31.18.31 ansible_ssh_user=ubuntu

[db:vars]
ansible_user=ec2-user
ansible_python_interpreter=/usr/bin/python

[db]
172.31.30.166 ansible_ssh_user=ubuntu