    pipeline {
    agent any

  stages {
     stage("Initial cleanup") {
      steps {
        dir("${WORKSPACE}") {
          deleteDir()
        }
      }
    }

    stage('Checkout SCM') {
      steps {
        git branch: 'main', credentialsId: 'gashity_token', url: 'https://github.com/AyopoB/ansible-config-mgt.git'
      }
    }
      stage('Test SSH Connection') {
            steps {
                sshagent(['private_key']) {  // 'ansible' is the ID of the credentials
                    sh 'ssh -o StrictHostKeyChecking=no ubuntu@172.31.41.146 exit'
                }
            }
        }
   


    stage('Run Ansible playbook') {
      steps {
       ansiblePlaybook credentialsId: 'private_key', disableHostKeyChecking: true, installation: 'ansible-config-mgt', inventory: 'inventory/dev.yml', playbook: 'playbooks/site.yml', vaultTmpPath: ''
      }
    }
      stage('Clean Workspace after build') {
      steps {
        cleanWs(cleanWhenAborted: true, cleanWhenFailure: true, cleanWhenNotBuilt: true, cleanWhenUnstable: true, deleteDirs: true)
      }
    }


    }
}

