---
mysql_root_password: ""
mysql_databases:
  - name: homestead
    encoding: utf8
    collation: utf8_general_ci

mysql_users:
  - name: homestead
    host: "172.31.16.0/20"
    password: Password.123
    priv: "*.*:ALL,GRANT"
