---
- name: update web and nfs servers
  hosts: webservers, nfs
  become: yes
  tasks:
    - name: ensure wireshark is at the latest version
      yum:
        name: wireshark
        state: latest

- name: update LB server, db
  hosts: lb,db
  become: yes
  tasks:
    - name: Update apt repo
      apt: 
        update_cache: yes

    - name: ensure wireshark is at the latest version
      apt:
        name: wireshark
        state: latest



- name: Create directory and file
  hosts: all
  become: yes
  tasks:
    - name: Create directory
      file:
        path: /etc/ansible-config
        state: directory
    - name: Create file inside the directory
      file:
        path: /etc/ansible-config/config.txt
        state: touch

- name: Change timezone to Lagos
  hosts: all
  become: yes
  tasks:
    - name: Set timezone to Africa/Lagos
      command: timedatectl set-timezone Africa/Lagos
